server_visa_application.server_visa_application_overview:
  path: '/visa-application'
  defaults:
    _controller: '\Drupal\server_visa_application\Controller\VisaApplicationForm::overview'
    _title: 'Visa Application Overview'
  requirements:
    _permission: 'access content'
    _custom_access: '\Drupal\server_visa_application\Controller\VisaApplicationForm::applicationFormAccess'
server_visa_application.server_visa_application_form:
  path: '/visa-application/{section_number}'
  defaults:
    _controller: '\Drupal\server_visa_application\Controller\VisaApplicationForm::main'
    _title: 'Visa Application'
  requirements:
    _permission: 'access content'
    _custom_access: '\Drupal\server_visa_application\Controller\VisaApplicationForm::applicationFormAccess'
    _role: 'authenticated'
    section_number: '[1-3]'
